package com.aaroncarsonart.quickgame2;

import org.omg.CORBA.UNKNOWN;

public enum PlayerAction {
    UP, DOWN, LEFT, RIGHT, OK, CANCEL, QUIT, WAIT,
    TOGGLE_AUTO_LOOT,
    CHEAT_LEVEL_UP, CHEAT_COLLECT_ITEMS, CHEAT_DRAW_ALL_SPRITES,
    MOVE_MENU, STATUS_MENU, INVENTORY_MENU, EQUIPMENT_MENU,
    UNKNOWN
}
